apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
    - image: gcr.io/homeserve-test-205811/skaffold
      context: .
      sync:
        '*.js': .
deploy:
  kubectl:
    manifests:
      - "k8s.yaml"